name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linting:
    name: Linting and Syntax Checking
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install linters
        run: |
          pip install flake8 yamllint

      - name: Run flake8
        run: flake8 --max-line-length=120 .

      - name: Run yamllint on k8s manifests
        run: yamllint kubernetes

  test:
    name: Run Python Tests
    runs-on: ubuntu-latest
    needs: linting
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies for tests
        run: |
          pip install pytest

      - name: Run pytest
        run: pytest -q

  build_and_push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & push parser-service image
        run: |
          docker build \
            --file parser_service/Dockerfile \
            --tag ntuckus/book-parser-service:latest \
            .
          docker push ntuckus/book-parser-service:latest

      - name: Build & push scraper image
        run: |
          docker build \
            --file scraper/Dockerfile \
            --tag ntuckus/book-scraper:latest \
            .
          docker push ntuckus/book-scraper:latest
